countme: fix ItemWriter 'tablename' traceback
I added `tablename` to `SQLiteWriter._get_writer()` so it could be used for
writing countme_raw and countme_totals, which broke non-SQLite writers:

  TypeError: _get_writer() got an unexpected keyword argument 'tablename'

This commit fixes the _get_writer() methods for the other classes so
they accept/ignore `tablename` and other unexpected keyword arguments.